### ISSUE TITLE
I'd be happy to take over this project

### ISSUE THREAD

**Issue by mattmcmanus** [mattmcmanus/atom-ember-snippets#16]
I've been using this repo plus a bunch of other snippets I've been maintaining for a while. If you're looking for a maintainer, I'd be happy to offer my services!

**Comment by seifsallam** [comment]
@mattmcmanus Yeah, that would be wonderful :)

**Comment by mattmcmanus** [comment]
Awesome. It depends on what you would prefer. Do you still want notifications and access and all that? If so, I'm more than happy as a collaborator. If you just want to be done, feel free to transfer it over. 

I'm not sure how permissions work for `apm` publishing. Since the atom api key is based on my github account, I suppose that should just work?

**Comment by seifsallam** [comment]
I've transferred the project to you. I don't know about `apm` but if there is any problem, we can transfer it back :)

**Comment by mattmcmanus** [comment]
Thanks @seifsallam!
