### ISSUE TITLE
Space between closing paren and bracket

### ISSUE THREAD

**Issue by samselikoff** [mattmcmanus/atom-ember-snippets#20]
Thanks for picking up maintenance of this lib :) 

Style bikeshed, how do you feel about adding a space after the parens in the method signatures?

```diff
-  didRender(){
+  didRender() {
     this._super(...arguments);
    
   },
```

**Comment by mattmcmanus** [comment]
Thanks @samselikoff. I thought that was the default, but a quick review of the snippets shows some inconsistency. I'll make the update.
