### ISSUE TITLE
No destructuring?

### ISSUE THREAD

**Issue by samselikoff** [mattmcmanus/atom-ember-snippets#24]
I did the destructuring thing for a while (`const { Component } = Ember;`) but it seems to have fallen out of favor. Wondering if we could/should switch back to Ember.Component, like in the guides?

Also I just saw this tweet: https://twitter.com/MiguelCamba/status/884724694871666688. It would be nice to add these soon, but I'm not sure about what they depend on.

**Comment by Exelord** [comment]
Yeah, I think it can be replaced with https://github.com/ember-cli/ember-rfc176-data

**Comment by mattmcmanus** [comment]
It's not out of favor until `ember-suave` says so! But seriously, that's we're I typically take my cues. 

Thanks for the link @Exelord. That should be easy enough to grep and make something useful. 

How would you want the snippet shorthands to work? I'm thinking something like prefixing all of them with `ime`. Something along the lines of: 

* `imea` -> `import EmberArray from "@ember/array"`
* `imer` -> `import { run } from "@ember/runloop"`

Thoughts?

**Comment by Exelord** [comment]
Now, even the official ember eslint plugin is saying so! :) https://github.com/ember-cli/eslint-plugin-ember/pull/90

**Comment by mattmcmanus** [comment]
I just shipped `2.1.0` which includes work done by @jbailey4 to merge in his `ember-module-snippets` into this plugin. I'll cut a `3.0.0` soon, which will update the existing file skeleton to use the new imports. 

Feedback welcome!
