### ISSUE TITLE
module imports do not appear to work on ember-cli-babel 6.12.0

### ISSUE THREAD

**Issue by billdami** [mattmcmanus/atom-ember-snippets#39]
Running in a ember-cli project that has ember-cli-babel v6.12.0 installed, I am not getting any autocomplete suggestions for ember module imports. However, on an older project, running 6.6.0, they are working fine.

If you need any additional environment info in order to debug this, just let me know.

**Comment by mattmcmanus** [comment]
Hey @billdami, The list of snippets is static. This addon, at this point, does no introspection on the current project. It's possible that you have a project specific atom setting that disabled the this addon? I'm not familiar with a feature like that, but that's all I can think of.

**Comment by billdami** [comment]
@mattmcmanus thanks for the response. For whatever reason, it just started working out of nowhere, ^_^  I forgot to close this out. It must've been something project or environment related on my end.
