### ISSUE TITLE
Remove Logger snippets

### ISSUE THREAD

**Issue by Exelord** [mattmcmanus/atom-ember-snippets#40]
We should remove all Logger references as it has been deprecated in favor of `console`
https://www.emberjs.com/blog/2018/07/02/ember-3-2-released.html#toc_use-of-ember-logger-1-of-3

https://github.com/mattmcmanus/atom-ember-snippets/blob/99eb8cdd7c9f6abb14a685cd611330b79a6ad0cd/snippets/ember.cson#L301-L326

**Comment by Exelord** [comment]
Why has it been closed?

**Comment by mattmcmanus** [comment]
https://github.com/mattmcmanus/atom-ember-snippets/commit/54857e51353cf3f019d0b7e22c6a510c8c02e4fb

Sorry, I thought it would have put some more useful info.

**Comment by Exelord** [comment]
The PR is still not merged

**Comment by mattmcmanus** [comment]
Published in `3.0.0`!
