### ISSUE TITLE
Change pauseTest snippet

### ISSUE THREAD

**Issue by Exelord** [mattmcmanus/atom-ember-snippets#41]
`await pauseTest()` should be changed to `await this.pauseTest()` as its assigned to context thanks to: https://github.com/emberjs/ember-qunit#setup-tests

Thanks to that, this call is more popular when debugging test

https://github.com/mattmcmanus/atom-ember-snippets/blob/99eb8cdd7c9f6abb14a685cd611330b79a6ad0cd/snippets/ember.cson#L362-L367

**Comment by mattmcmanus** [comment]
Published in `3.0.0`!
