### ISSUE TITLE
Add LET helper to templates snippets

### ISSUE THREAD

**Issue by Exelord** [mattmcmanus/atom-ember-snippets#42]
It would be useful to add new `let` helper snippet
REF: https://github.com/emberjs/rfcs/blob/master/text/0286-block-let-template-helper.md

https://github.com/mattmcmanus/atom-ember-snippets/blob/99eb8cdd7c9f6abb14a685cd611330b79a6ad0cd/snippets/handlebars.cson#L3

**Comment by mattmcmanus** [comment]
Published in `3.0.0`!
