### ISSUE TITLE
Improve inject.service snippet

### ISSUE THREAD

**Issue by Exelord** [mattmcmanus/atom-ember-snippets#43]
as `iminjectService` adds: `import { inject as service } from '@ember/service';` it makes sense to change this snippet to just `service(${1}),`

https://github.com/mattmcmanus/atom-ember-snippets/blob/99eb8cdd7c9f6abb14a685cd611330b79a6ad0cd/snippets/ember.cson#L66-L69

**Comment by Exelord** [comment]
Why its closed? Its not fixed

**Comment by mattmcmanus** [comment]
Hey @Exelord, make sure to check the recent commits: https://github.com/mattmcmanus/atom-ember-snippets/commit/306760aa33080ed1b73fc85e1f5baf458e5c214f

I'm going to thrashing in here for a little bit making a bunch of tweaks. I should I have a release out before I wrap up for the night.

**Comment by mattmcmanus** [comment]
Published in `3.0.0`!
