### ISSUE TITLE
Await tests helpers

### ISSUE THREAD

**Issue by Exelord** [mattmcmanus/atom-ember-snippets#44]
Now it makes sense to put `await` before every helper as they are async Promises 

https://github.com/mattmcmanus/atom-ember-snippets/blob/99eb8cdd7c9f6abb14a685cd611330b79a6ad0cd/snippets/ember.cson#L332-L360

**Comment by Exelord** [comment]
The package should always follow the latest trends.

**Comment by mattmcmanus** [comment]
@Exelord and @jrock2004: That's a tough call. I'm doing some work on this tonight so I'll think it through. Right now, I'm thinking I'll use the newest patterns with the option to select the `awaits\` at the end and remove them if you want. Another option is to prefix the snippets with `a`, so `avisit` would do `await visit($1)` and `visit` would the plain ol' one. Feel free to weigh in!

**Comment by Exelord** [comment]
I think we should just move forward. This pattern is already over 1 year old. We should push users to upgrade as this is almost at no cost.

**Comment by mattmcmanus** [comment]
@Exelord Agreed. I'm in the process of bringing in snippets for most of the ember-test-snippets package.

**Comment by mattmcmanus** [comment]
Published in `3.0.0`!
