### ISSUE TITLE
Update Model snippet

### ISSUE THREAD

**Issue by Exelord** [mattmcmanus/atom-ember-snippets#45]
Import of `DS.Model` should be changed to `import Model from 'ember-data/model';`

https://github.com/mattmcmanus/atom-ember-snippets/blob/99eb8cdd7c9f6abb14a685cd611330b79a6ad0cd/snippets/file-skeletons.cson#L104-L113

**Comment by jrock2004** [comment]
@Exelord looking here https://guides.emberjs.com/release/models/defining-models/ it seems like what is already there is in place

**Comment by Exelord** [comment]
The Guides are outdated. The way I mentioned higher is the recommended one.

**Comment by Exelord** [comment]
Fixed in #47

**Comment by mattmcmanus** [comment]
Published in `3.0.0`!
